<!-- This script contains code to build a web page with a form. It includes a PHP code to dynamically generate the html to display one checkbox for each of the toys currently held in the NMC_records database table within the form. The user can select one or more records that they are interested in ordering by clicking the checkboxes. Use the browser to look at the structure of the html generated by the php code.

You MUST NOT in any way change the php code provided OR the code within the FORM tags.

You MAY add Javascript for task 4.
You MAY modify the page to add your own navigation menu and link to your own stylesheet using additional html or php. However, please note that styling will not be marked for this assignment. -->

<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Order Records</title>
	
	<!--*********************************************************************** -->
	<!--Added code for CSS-->
	<link href=review.css rel="stylesheet" type="text/css">
	<!--*********************************************************************** -->

</head>
<body>
<!--***********************************************************************-->
<!--Added code for CSS-->
<!-- include the file with the function for the database connection-->
<?php
    /*Session initialization for login*/
	ini_set("session.save_path", "/home/unn_w22034009/sessionData");
    session_start();

	require_once('functions.php');
	echo "<div id='gridContainer'>";

    /*Displaying the login form or log out option in nav menu*/
	echo makeHeader("Task 4");
	if(checkLogin()){
        echo makeNavMenu("Options", array("home.php" => "Home Page", "logout.php" => "Log out","index.php" => "Update","orderRecordsForm.php" => "Order Records", "credits.php" => "Credits"), true);
    }else{
        echo makeNavMenu("Options", array("home.php" => "Home Page","index.php" => "Update","orderRecordsForm.php" => "Order Records", "credits.php" => "Credits"), false);
    }
    echo startMain();
   ?>
<!--***********************************************************************-->

<h1>Order Recordss</h1>

<form id="orderForm" action="javascript:alert('form submitted');" method="get">
	<section id="orderRecords">
		<h2>Select Records</h2>
<?php
try {
	
	// get database connection
	$dbConn = getConnection();
	$sqlRecords = 'SELECT recordID, recordTitle, catDesc, pubName, recordPrice FROM nmc_records r INNER JOIN nmc_category c ON r.catID = c.catID INNER JOIN nmc_publisher p ON r.pubID = p.pubID ORDER BY recordTitle';

	// execute the query
	$rsRecords = $dbConn->query($sqlRecords);

	while ($record = $rsRecords->fetchObject()) {
		$recordTitle = $record->recordTitle;
		echo "\t<div class='item'>
				<span class='recordTitle'>".filter_var($recordTitle, FILTER_SANITIZE_SPECIAL_CHARS)."</span>
	            <span class='catDesc'>{$record->catDesc}</span>
	         	<span class='pubName'>{$record->pubName}</span>
	            <span class='recordPrice'>{$record->recordPrice}</span>
	            <span class='chosen'><input type='checkbox' name='record[]' value='{$record->recordID}' data-price='{$record->recordPrice}'></span>
	      		</div>\n";
	}
}
catch (Exception $e) {
	echo "Problem " . $e->getMessage();
}
?>
	</section>
	<section id="collection">
		<h2>Collection method</h2>
		<p>Please select whether you want your chosen record(s) to be delivered to your home address (a charge applies for this) or whether you want to collect them yourself.</p>
		<p>
		Home address - &pound;4.99 <input type="radio" name="deliveryType" value="home" data-price="4.99" checked>&nbsp; | &nbsp;
		Collect from shop - no charge <input type="radio" name="deliveryType" value="shop" data-price="0">
		</p>
	</section>
	<section id="checkCost">
		<h2>Total cost</h2>
		Total <input type="text" name="total" size="10" readonly>
	</section>
	<section id="placeOrder">
		<h2>Place Order</h2>
		<h3>Your details</h3>
		<div id="retCustDetails" class="custDetails">
			Forename <input type="text" name="forename">
			Surname <input type="text" name="surname">
		</div>
		<p style="color: #FF0000; font-weight: bold;" id='termsText'>I have read and agree to the terms and conditions
		<input type="checkbox" name="termsChkbx"></p>
		<p><input type="submit" name="submit" value="Order now!" disabled></p>
	</section>
</form>	
<!-- Here you need to add Javascript or a link to a script (.js file) to process the form as required for task 4 of the assignment -->
<script type="text/javascript" src="formProcess.js"></script>

<!--*********************************************************************** -->
<!--Added code for CSS-->
<?php
	echo endMain();
	echo "</div>";
	echo makeFooter("KF5002 Assignment");
?>
<!--*********************************************************************** -->


</body>
</html>